-- Generated by LuaPadEmmyApiGenerator. Do not edit.
---@diagnostic disable: missing-return, undefined-doc-name, undefined-doc-class
---@class LuaUiUtil
---@field InstantiateUnder fun(prefabPath: string, parent: UnityEngine.Transform): LuaUiComponent
---@field SetRaycasterEnabled fun(canvasGo: UnityEngine.GameObject, enabled: boolean)
local _ = {}
---@alias CS.LuaUiUtil LuaUiUtil
