-- Generated by LuaPadEmmyApiGenerator. Do not edit.
---@diagnostic disable: missing-return, undefined-doc-name, undefined-doc-class
---@class UnityEngine.UI.Button : UnityEngine.UI.Selectable
---@field onClick UnityEngine.UI.Button.ButtonClickedEvent
---@field OnPointerClick fun(self: UnityEngine.UI.Button, eventData: UnityEngine.EventSystems.PointerEventData)
---@field OnSubmit fun(self: UnityEngine.UI.Button, eventData: UnityEngine.EventSystems.BaseEventData)
local _ = {}
---@alias CS.UnityEngine.UI.Button UnityEngine.UI.Button
