-- Generated by LuaPadEmmyApiGenerator. Do not edit.
---@diagnostic disable: missing-return, undefined-doc-name, undefined-doc-class
---@class UnityEngine.Behaviour : UnityEngine.Component
---@overload fun(): UnityEngine.Behaviour
---@field enabled boolean
---@field isActiveAndEnabled boolean
local _ = {}
---@alias CS.UnityEngine.Behaviour UnityEngine.Behaviour
