// <auto-generated />
using System;
using AChen.Backend.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AChen.Backend.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902150000_PlayerOwnedAvatarIds")]
    partial class PlayerOwnedAvatarIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("AChen.Backend.Api.Features.Auth.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshSessions");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.ContentDelivery.ActiveContentRelease", b =>
                {
                    b.Property<string>("Channel")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Channel", "Platform", "AppVersion");

                    b.HasIndex("ReleaseId");

                    b.ToTable("ActiveContentReleases");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.ContentDelivery.ContentPublication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PreviousReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PreviousReleaseId");

                    b.HasIndex("ReleaseId");

                    b.HasIndex("Channel", "Platform", "AppVersion", "CreatedAt");

                    b.ToTable("ContentPublications");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.ContentDelivery.ContentRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactSha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CatalogHashPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CatalogPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("FileCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HotUpdatePath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReadyAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Platform", "AppVersion", "ContentVersion")
                        .IsUnique();

                    b.ToTable("ContentReleases");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.ContentDelivery.ContentReleaseFile", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReleaseId", "RelativePath");

                    b.ToTable("ContentReleaseFiles");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.GameConfig.AvatarDefinition", b =>
                {
                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Revision", "Id");

                    b.HasIndex("Revision", "ResourceKey")
                        .IsUnique();

                    b.HasIndex("Revision", "SortOrder", "Id");

                    b.ToTable("AvatarDefinitions", t =>
                        {
                            t.HasCheckConstraint("CK_AvatarDefinitions_Id_Positive", "Id > 0");
                        });
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.GameConfig.CardPackDefinition", b =>
                {
                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverResourceKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("EndsAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PriceGold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StartsAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Revision", "Id");

                    b.HasIndex("Revision", "SortOrder", "Id");

                    b.ToTable("CardPackDefinitions", t =>
                        {
                            t.HasCheckConstraint("CK_CardPackDefinitions_Id_Positive", "Id > 0");

                            t.HasCheckConstraint("CK_CardPackDefinitions_PriceGold_NonNegative", "PriceGold >= 0");
                        });
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.GameConfig.GameConfigVersion", b =>
                {
                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EditRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PublishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Revision");

                    b.HasIndex("State")
                        .IsUnique()
                        .HasFilter("\"State\" = 'Draft'");

                    b.ToTable("GameConfigVersions", t =>
                        {
                            t.HasCheckConstraint("CK_GameConfigVersions_EditRevision_NonNegative", "EditRevision >= 0");
                        });
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Players.PlayerProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AvatarId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BackgroundId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnedAvatarIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("PlayerProfiles", t =>
                        {
                            t.HasCheckConstraint("CK_PlayerProfiles_Gold_NonNegative", "Gold >= 0");
                        });
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Auth.RefreshSession", b =>
                {
                    b.HasOne("AChen.Backend.Api.Features.Auth.User", "User")
                        .WithMany("RefreshSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.ContentDelivery.ActiveContentRelease", b =>
                {
                    b.HasOne("AChen.Backend.Api.Features.ContentDelivery.ContentRelease", "Release")
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.ContentDelivery.ContentPublication", b =>
                {
                    b.HasOne("AChen.Backend.Api.Features.ContentDelivery.ContentRelease", "PreviousRelease")
                        .WithMany()
                        .HasForeignKey("PreviousReleaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AChen.Backend.Api.Features.ContentDelivery.ContentRelease", "Release")
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PreviousRelease");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.ContentDelivery.ContentReleaseFile", b =>
                {
                    b.HasOne("AChen.Backend.Api.Features.ContentDelivery.ContentRelease", "Release")
                        .WithMany("Files")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.GameConfig.AvatarDefinition", b =>
                {
                    b.HasOne("AChen.Backend.Api.Features.GameConfig.GameConfigVersion", "Version")
                        .WithMany("Avatars")
                        .HasForeignKey("Revision")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.GameConfig.CardPackDefinition", b =>
                {
                    b.HasOne("AChen.Backend.Api.Features.GameConfig.GameConfigVersion", "Version")
                        .WithMany("CardPacks")
                        .HasForeignKey("Revision")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Players.PlayerProfile", b =>
                {
                    b.HasOne("AChen.Backend.Api.Features.Auth.User", "User")
                        .WithOne("PlayerProfile")
                        .HasForeignKey("AChen.Backend.Api.Features.Players.PlayerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.Auth.User", b =>
                {
                    b.Navigation("PlayerProfile");

                    b.Navigation("RefreshSessions");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.ContentDelivery.ContentRelease", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("AChen.Backend.Api.Features.GameConfig.GameConfigVersion", b =>
                {
                    b.Navigation("Avatars");

                    b.Navigation("CardPacks");
                });
#pragma warning restore 612, 618
        }
    }
}
