-- Generated by LuaPadEmmyApiGenerator. Do not edit.
---@diagnostic disable: missing-return, undefined-doc-name, undefined-doc-class
---@class UnityEngine.UI.RawImage : UnityEngine.UI.MaskableGraphic
---@field mainTexture UnityEngine.Texture
---@field texture UnityEngine.Texture
---@field uvRect UnityEngine.Rect
---@field SetNativeSize fun(self: UnityEngine.UI.RawImage)
local _ = {}
---@alias CS.UnityEngine.UI.RawImage UnityEngine.UI.RawImage
