"""Generate the public declaration-name C# data from the existing versioned CSV.

No game runtime dependency on an external CDB or CSV parser is introduced.
"""
import argparse
import csv
import hashlib
import json
from pathlib import Path


def generate(root):
    with (root / "TableData/card-name-catalog.csv").open(encoding="utf-8-sig", newline="") as stream:
        rows = list(csv.DictReader(stream))[1:]
    rows.sort(key=lambda row: row["NameId"])
    canonical = json.dumps(rows, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")
    fingerprint = hashlib.sha256(canonical).hexdigest()
    quote = lambda value: json.dumps(value, ensure_ascii=False)
    output = ["// Generated by Tools/Duel/generate_name_catalog.py from TableData/card-name-catalog.csv.",
              "using System.Collections.Generic;", "namespace AChen.Duel.Core", "{",
              "    internal static class CardNameCatalogData", "    {",
              "        public const string Fingerprint = " + quote(fingerprint) + ";",
              "        public static CardNameDefinition[] CreateNames()", "        {",
              "            var names = new List<CardNameDefinition>(" + str(len(rows)) + ");"]
    chunks = [rows[start:start + 256] for start in range(0, len(rows), 256)]
    for index in range(len(chunks)):
        output.append("            Append" + str(index) + "(names);")
    output.extend(["            return names.ToArray();", "        }"])
    for index, chunk in enumerate(chunks):
        output.extend(["        static void Append" + str(index) + "(List<CardNameDefinition> names)", "        {"])
        for row in chunk:
            kind = {"1": "Monster", "2": "Spell", "3": "Trap"}[row["Kind"]]
            values = [quote(row[key]) for key in ("NameId", "Japanese", "Chinese", "English")]
            output.append("            names.Add(new CardNameDefinition(" + values[0] + ", RuleCardKind." + kind
                          + ", " + ", ".join(values[1:]) + "));")
        output.append("        }")
    output.extend(["    }", "}", ""])
    destination = root / "Assets/Scripts/Duel/Shared/Cards/CardNameCatalogData.Generated.cs"
    destination.write_text("\n".join(output), encoding="utf-8", newline="\n")
    return fingerprint


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args()
    print(generate(args.project_root))
