using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;

/// <summary>
/// 按 xLua 反射可见的 C# 类型生成 EmmyLua ---@class 桩，供 Lua Pad / emmylua_ls 补全。
/// </summary>
public static class LuaPadEmmyApiGenerator
{
    public const string RelativeDir = "Assets/Scripts/LuaRaw/EmmyApi";

    static readonly HashSet<string> LuaKeywords = new HashSet<string>
    {
        "and", "break", "do", "else", "elseif", "end", "false", "for", "function",
        "goto", "if", "in", "local", "nil", "not", "or", "repeat", "return", "then",
        "true", "until", "while",
    };

    [MenuItem("Tools/Lua/Generate EmmyLua API")]
    public static void GenerateMenu()
    {
        int n = Generate();
        AssetDatabase.Refresh();
        Debug.Log("[LuaPad] EmmyLua API 已生成 " + n + " 个类型 → " + RelativeDir);
    }

    public static int Generate()
    {
        string dir = Path.GetFullPath(RelativeDir);
        if (Directory.Exists(dir))
        {
            Directory.Delete(dir, true);
        }
        Directory.CreateDirectory(dir);
        var types = CollectTypes();
        foreach (Type type in types)
        {
            File.WriteAllText(Path.Combine(dir, FileName(type)), Render(type), Encoding.UTF8);
        }
        return types.Count;
    }

    public static string Render(Type type)
    {
        string name = LuaName(type);
        var sb = new StringBuilder();
        sb.AppendLine("-- Generated by LuaPadEmmyApiGenerator. Do not edit.");
        sb.AppendLine("---@diagnostic disable: missing-return, undefined-doc-name, undefined-doc-class");
        sb.Append("---@class ").Append(name);
        Type parent = type.BaseType;
        if (parent != null && parent != typeof(object) && parent != typeof(ValueType) && parent != typeof(Enum))
        {
            sb.Append(" : ").Append(LuaName(parent));
        }
        sb.AppendLine();
        foreach (ConstructorInfo ctor in type.GetConstructors(BindingFlags.Public | BindingFlags.Instance))
        {
            if (SkipMember(ctor))
            {
                continue;
            }
            sb.Append("---@overload fun(").Append(Params(ctor.GetParameters(), false)).Append("): ").Append(name).Append('\n');
        }
        const BindingFlags flags = BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly;
        foreach (FieldInfo field in type.GetFields(flags))
        {
            if (SkipMember(field) || !IsIdent(field.Name))
            {
                continue;
            }
            sb.Append("---@field ").Append(field.Name).Append(' ').Append(LuaType(field.FieldType)).Append('\n');
        }
        foreach (PropertyInfo prop in type.GetProperties(flags))
        {
            if (SkipMember(prop) || prop.GetIndexParameters().Length > 0 || !IsIdent(prop.Name))
            {
                continue;
            }
            sb.Append("---@field ").Append(prop.Name).Append(' ').Append(LuaType(prop.PropertyType)).Append('\n');
        }
        foreach (MethodInfo method in type.GetMethods(flags))
        {
            if (method.IsSpecialName || SkipMember(method) || !IsIdent(method.Name))
            {
                continue;
            }
            sb.Append("---@field ").Append(method.Name).Append(" fun(");
            sb.Append(Params(method.GetParameters(), !method.IsStatic, name));
            sb.Append(')');
            if (method.ReturnType != typeof(void))
            {
                sb.Append(": ").Append(LuaType(method.ReturnType));
            }
            sb.Append('\n');
        }
        sb.AppendLine("local _ = {}");
        sb.Append("---@alias CS.").Append(name).Append(' ').Append(name).Append('\n');
        return sb.ToString();
    }

    public static string LuaType(Type type)
    {
        if (type == typeof(void))
        {
            return "nil";
        }
        if (type == typeof(string) || type == typeof(char))
        {
            return "string";
        }
        if (type == typeof(bool))
        {
            return "boolean";
        }
        if (type.IsPrimitive)
        {
            return "number";
        }
        if (type == typeof(object))
        {
            return "any";
        }
        if (type.IsByRef)
        {
            return LuaType(type.GetElementType());
        }
        if (type.IsArray)
        {
            return LuaType(type.GetElementType()) + "[]";
        }
        return LuaName(type);
    }

    public static string LuaName(Type type)
    {
        if (type == null || string.IsNullOrEmpty(type.FullName))
        {
            return "any";
        }
        string name = type.FullName;
        int tick = name.IndexOf('`');
        if (tick >= 0)
        {
            name = name.Substring(0, tick);
        }
        return name.Replace('+', '.');
    }

    static string FileName(Type type)
    {
        return LuaName(type).Replace('.', '_') + ".lua";
    }

    static List<Type> CollectTypes()
    {
        var set = new HashSet<Type>();
        Add(set, typeof(GameObject));
        Add(set, typeof(Transform));
        Add(set, typeof(Component));
        Add(set, typeof(Behaviour));
        Add(set, typeof(MonoBehaviour));
        Add(set, typeof(UnityEngine.Object));
        Add(set, typeof(Resources));
        Add(set, typeof(Color));
        Add(set, typeof(Vector2));
        Add(set, typeof(Vector3));
        Add(set, typeof(Quaternion));
        Add(set, typeof(Time));
        Add(set, typeof(Mathf));
        Add(set, typeof(Debug));
        Add(set, typeof(Application));
        Add(set, typeof(ALog));
        Add(set, typeof(LuaUiUtil));
        Add(set, typeof(LuaUiComponent));
        var list = new List<Type>(set);
        list.Sort((a, b) => string.CompareOrdinal(LuaName(a), LuaName(b)));
        return list;
    }

    static void Add(HashSet<Type> set, Type type)
    {
        if (type == null || type.IsGenericTypeDefinition || type.IsGenericParameter || !type.IsPublic)
        {
            return;
        }
        if (type.IsEnum || type.IsPrimitive || type == typeof(string) || type == typeof(object) || type == typeof(void))
        {
            return;
        }
        if (typeof(Delegate).IsAssignableFrom(type))
        {
            return;
        }
        if (type.GetCustomAttribute<ObsoleteAttribute>() != null)
        {
            return;
        }
        set.Add(type);
    }

    static bool SkipMember(MemberInfo member)
    {
        return member.GetCustomAttribute<ObsoleteAttribute>() != null;
    }

    static bool IsIdent(string name)
    {
        if (string.IsNullOrEmpty(name) || LuaKeywords.Contains(name))
        {
            return false;
        }
        char c = name[0];
        if (!(c == '_' || (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z')))
        {
            return false;
        }
        for (int i = 1; i < name.Length; i++)
        {
            c = name[i];
            if (!(c == '_' || (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9')))
            {
                return false;
            }
        }
        return true;
    }

    static string Params(ParameterInfo[] args, bool withSelf, string selfType = null)
    {
        var sb = new StringBuilder();
        if (withSelf)
        {
            sb.Append("self: ").Append(selfType);
        }
        for (int i = 0; i < args.Length; i++)
        {
            if (sb.Length > 0)
            {
                sb.Append(", ");
            }
            string n = IsIdent(args[i].Name) ? args[i].Name : "p" + i;
            sb.Append(n).Append(": ").Append(LuaType(args[i].ParameterType));
        }
        return sb.ToString();
    }
}
